### ISSUE TITLE
Switching from React.js to Next.js to improve performance and functionality

### ISSUE THREAD

**Issue by Roaaabdullah** [hatimalattas/y#12]
Our current chat app is built using React.js. However, recent developments and community support indicate a significant shift toward Next.js. This shift is due to Next.js's enhanced features, better performance, and improved SEO capabilities.

**Comment by hatimalattas** [comment]
Couldn't agree more, Roaa! It's better to be aligned with what React team is recommending. Going with NextJS will provide us with powerful out of the box capabilities, such as routing, data fetching, SSR, and it will be a great learning experience for us.
